"project_id" : "416630"
"base_url" : "https://api.crowdin.com"
"preserve_hierarchy": true
files: [
 {
  "source" : "admin-pages/messages/en.json",
  "translation" : "admin-pages/messages/%two_letters_code%.json",
  "type" : "json",
 }
]